name: CI

on:
  pull_request:
    branches:
      - main
env:
  project-directory: ./
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: yarn clean install
        run: yarn ci

      - name: Typescript compiles
        run: yarn build

      - name: Lint
        run:
          yarn lint

          # Install and cache NPM dependencies, run integration tests
      - name: Cypress E2E (Dev Server) 🧪
        uses: cypress-io/github-action@v2
        with:
          # run these before testing
          start: |
            yarn dev
          # wait for server to be ready
          wait-on: 'http://localhost:3000'

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn cypress run-ct

      - name: run tests
        run: yarn test
